name: Build Keyboards

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-rp2040-3x3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build rp2040_3x3
        run: |
          make rp2040_3x3:default

  build-rp2040-2x3-encoder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build rp2040_2x3_encoder
        run: |
          make rp2040_2x3_encoder:via

  build-promicro-4x6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build promicro_handwired_4x6
        run: |
          make promicro_handwired_4x6:default
